### ISSUE TITLE
Bug: Not all stores are found when scraping with Metadata

### ISSUE THREAD

**Issue by Ernir** [davidarnarsson/vinbud-scraper#6]
_Problem description:_ The scraper sometimes passes over about half the entries of the "stock status" tables.

For example, this is my last scrape for [Víking Gylltur](http://www.vinbudin.is/DesktopDefault.aspx/tabid-54?productID=01484) (pardon my output structure):

```
"availability": [
        {
            "region": "HÖFUÐBORGARSVÆÐIÐ",
            "stores": [
                {
                    "numberInStock": 628,
                    "store": "Austurstræti"
                },
                {
                    "numberInStock": 1068,
                    "store": "Kringlunni"
                },
                {
                    "numberInStock": 2046,
                    "store": "Skeifunni"
                },
                {
                    "numberInStock": 1406,
                    "store": "Stekkjarbakka"
                },
                {
                    "numberInStock": 2405,
                    "store": "Dalvegi"
                },
                {
                    "numberInStock": 196,
                    "store": "Smáralind"
                }
            ]
```

But in fact, the swill is available pretty much everywhere, not just those 6 stores.

_Probable cause:_ I'm guessing the scraper only pulls information from the first set of columns, but ÁTVR sometimes arranges the stock information into two sets of columns (separated by a friggin'  `&nbsp;`).

_Possible fix:_ Not quite sure how to best fix the crawler, I'm still not really comfortable with PhantomJS. :P

**Comment by davidarnarsson** [comment]
I have a fix for this in the works. I shall push it to github once I finish some more refactorings. I'm also adding some tests for both node-compliant code and phantomjs-dependant code (including a regression test for this bug).

**Comment by Ernir** [comment]
Any news on this front? :)

**Comment by davidarnarsson** [comment]
This should be fixed in master now.
